
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'demo'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'demo'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  demo:
    # Config indicated by + and applies to all files under models/example/
    example:
      +materialized: view

    # Staging models
    staging:
      +materialized: view
      +tags:
        - staging

    # Intermediate models
    intermediate:
      +materialized: view
      +tags:
        - intermediate

    # Marts models
    marts:
      +materialized: table
      +tags:
        - marts

      # Sales mart
      sales:
        # Incremental fact table for customer lifetime aggregations
        fct_customer_orders:
          +materialized: incremental
          +unique_key: customer_key
          +on_schema_change: sync_all_columns
          +tags:
            - incremental
            - customer_lifetime
