version: 2

models:
  - name: mart_customer_orders
    description: "顧客別注文集計（完了注文のみ）"
    columns:
      - name: customer_id
        description: "顧客ID（PK）"
        data_tests:
          - not_null
          - unique

      - name: customer_name
        description: "顧客名"
        data_tests:
          - not_null

      - name: region
        description: "地域"
        data_tests:
          - not_null
          - accepted_values:

              values: ['東京', '大阪', '福岡', '名古屋', '札幌']

      - name: order_count
        description: "注文件数"
        data_tests:
          - not_null

      - name: total_amount
        description: "合計金額"
        data_tests:
          - not_null

      - name: avg_amount
        description: "平均金額"

  - name: mart_order_summary
    description: "日次の注文サマリ（注文数、顧客数、売上合計など）"
    columns:
      - name: order_date
        description: "注文日"
        tests:
          - not_null
          - unique
      - name: total_orders
        description: "注文数"
        tests:
          - not_null
      - name: total_revenue
        description: "売上合計"
        tests:
          - not_null